### ISSUE TITLE
你好,我持续关注中文汉字汉语编程,所以想就此次事件发表一些看法,

### ISSUE THREAD

**Issue by qwas982** [MulanRevive/bounty#2]
你好,我持续关注中文汉字汉语编程,所以想就此次事件发表一些看法,
与其悬赏,不如创立工作室,写企划,拉风投,开始真正的中文编程事业,我一定会加入你的团队,贡献自己的力量.
不过我最近还在学习算法和antlr4,但我一直在探索中文编程相关道路.
因为现实生活条件环境所限,我不可能全时投入学习和专注在中文编程事业之上,
所以这么多年来,我进步缓慢.
但我还是坚持'编程技术普及化','编程文化大众化',这样的愿景.

借'木兰'被舆论倒风之机,
追逐中文编程方向的朋友们聚集在一起,讨论实现中文编程生态,
万事开头难,先从讨论语言规格开始如何?

**Comment by nobodxbodon** [comment]
此处不进行与木兰编程语言和编译器实现的无关讨论，谢谢。

**Comment by qwas982** [comment]
噢,好吧.
