### ISSUE TITLE
请问重金具体是指什么，又是为了什么

### ISSUE THREAD

**Issue by duangsuse** [MulanRevive/bounty#9]
而且，是否和原来木兰过度宣传的缘由如出一辙呢？

**Comment by nobodxbodon** [comment]
”重金“和本项目目标见项目首页。

至今为止对木兰项目的了解都集合在[原始资料](https://github.com/MulanRevive/bounty/tree/master/%E5%8E%9F%E5%A7%8B%E8%B5%84%E6%96%99)。如对木兰项目有其他细节了解，欢迎分享并注明来源。
